language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  include:
    - php: 5.3
      env: 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'

  allow_failures:
    - php: 7.0
    - php: hhvm

before_script:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs --standard=phpcs.xml lib/
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
    - bash <(curl -s https://codecov.io/bash)